<?PHP
session_start();
$username=$_POST['username'];
$password=$_POST['password'];
$con=mysqli_connect('localhost','root','');
mysqli_select_db($con,'user');
$q="select * from details where USERNAME='$username' AND PASSWORD='$password'";
$result=mysqli_query($con,$q);
$num=mysqli_num_rows($result);
if($num==1)
{
 $_SESSION['username']=$username;
 header('location:http://localhost/insert/home1.php');
}
else
{
  header('location:http://localhost/insert/login.php');	
}
?>